### PR TITLE
Update README.md to document usage in marimo

### PR DESCRIPTION
**Pull request by akshayka**
Let quak users know how they can use quak in marimo.

### CODE REVIEW

**Comment by manzt** [comment]
Nice! Do you have any badge or link to open the example in marimo playground?

**Comment by akshayka** [comment]
Just tried, but it looks like `pyarrow` is not yet supported on Pyodide.

Maybe soon though? https://github.com/pyodide/pyodide/pull/4950

**Comment by manzt** [comment]
ahhh right, @kylebarron ... would this be an area where py03-arrow could help out? or does duckdb rely on pyarrow internally?

**Comment by akshayka** [comment]
duckdb is in fact now available in Pyodide; Polars still isn't, though.

**Comment by kylebarron** [comment]
Right. Polars would need quite a few architectural changes to support pyodide. I explored this a while ago: https://github.com/pola-rs/polars/issues/3672#issuecomment-1188641190

**Pull request merged**
