### PR TITLE
chore: Switch from rye to uv for development

### PR DESCRIPTION
**Pull request by manzt**

### CODE REVIEW

**Comment by domoritz** [comment]
So you use hatch and uv after this change? What does hatch do that uv doesn't?

**Comment by manzt** [comment]
> So you use hatch and uv after this change? What does hatch do that uv doesn't?

Nope, no hatch at all. All the hatch config is just for the hatchling build process. It's all uv.

**Comment by manzt** [comment]
@domoritz Also quak is a place where I'm trying out some new ideas for flows and tools for developing widgets... so please take the actions here with a grain of salt. My hope is that I settle on something that I can try to recommend to the community.

**Comment by domoritz** [comment]
That's awesome. I've learned a lot from your setups.

**Pull request merged**
